// styles/EmotionSelectorStyles.js
import { StyleSheet } from 'react-native';
import customFont from './fonts';

export const emotionSelectorStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backButton: {
        padding: 10,
    },
    saveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E57373',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 6,
        fontFamily: customFont,
    },
    titleContainer: {
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    title: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333333',
        marginBottom: 4,
        fontFamily: customFont,
    },
    subtitle: {
        fontSize: 14,
        color: '#E57373',
        fontFamily: customFont,
    },
    emotionStats: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
        backgroundColor: '#FAFAFA',
        maxHeight: 200,
    },
    statsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    statsTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333333',
        fontFamily: customFont,
    },
    statsCount: {
        backgroundColor: '#E57373',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
        minWidth: 24,
        alignItems: 'center',
    },
    statsCountText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '700',
        fontFamily: customFont,
    },
    statsList: {
        maxHeight: 140,
    },
    statsItem: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
        marginBottom: 8,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    statsIndicator: {
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 6,
        minWidth: 60,
        alignItems: 'center',
        marginRight: 12,
    },
    statsIndicatorText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
        fontFamily: customFont,
    },
    statsContent: {
        flex: 1,
        marginRight: 8,
    },
    statsText: {
        fontSize: 14,
        color: '#333333',
        lineHeight: 20,
        marginBottom: 4,
        fontFamily: customFont,
    },
    statsPosition: {
        fontSize: 11,
        color: '#999999',
        fontFamily: customFont,
    },
    bottomSelectionBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
        paddingHorizontal: 20,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 8,
    },
    bottomContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    selectedTextInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
    },
    bottomText: {
        flex: 1,
        fontSize: 13,
        color: '#666666',
        fontStyle: 'italic',
        marginLeft: 8,
        fontFamily: customFont,
    },
    bottomButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E57373',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
    },
    bottomButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 6,
        fontFamily: customFont,
    },
});
