// styles/components/AICommentReviewStyles.js
import { StyleSheet } from 'react-native';
import customFont from '../fonts';

export const aiCommentReviewStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    headerTitle: {
        fontSize: 18,
        color: '#333333',
        fontFamily: customFont,
        fontWeight: '600',
    },
    saveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FB644C',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 20,
    },
    saveButtonDisabled: {
        backgroundColor: '#CCCCCC',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
    },
    loadingText: {
        fontSize: 16,
        color: '#666666',
        marginTop: 20,
        textAlign: 'center',
        fontFamily: customFont,
    },
    progressContainer: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#F8F8F8',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    progressText: {
        fontSize: 14,
        color: '#FB644C',
        textAlign: 'center',
        fontFamily: customFont,
        fontWeight: '600',
    },
    titleContainer: {
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    title: {
        fontSize: 22,
        color: '#333333',
        fontFamily: customFont,
        fontWeight: '600',
    },
    scrollView: {
        flex: 1,
        paddingHorizontal: 20,
    },
    contentContainer: {
        paddingVertical: 20,
    },
    contentText: {
        fontSize: 18,
        lineHeight: 26,
        color: '#333333',
        fontFamily: customFont,
    },
    commentIcon: {
        marginLeft: 4,
        marginRight: 4,
        padding: 2,
    },
    guideContainer: {
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: '#FFF7E6',
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    guideText: {
        fontSize: 14,
        color: '#D86B00',
        textAlign: 'center',
        fontFamily: customFont,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginHorizontal: 20,
        maxWidth: 350,
        width: '100%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        color: '#333333',
        fontFamily: customFont,
        fontWeight: '600',
    },
    modalContent: {
        marginBottom: 20,
    },
    targetText: {
        marginBottom: 15,
        padding: 12,
        backgroundColor: '#F8F8F8',
        borderRadius: 8,
    },
    targetLabel: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 6,
        fontFamily: customFont,
    },
    targetContent: {
        fontSize: 16,
        color: '#333333',
        fontFamily: customFont,
    },
    commentContent: {
        padding: 12,
        backgroundColor: '#FFF7E6',
        borderRadius: 8,
        borderLeftWidth: 4,
        borderLeftColor: '#FB644C',
    },
    commentLabel: {
        fontSize: 14,
        color: '#D86B00',
        marginBottom: 6,
        fontFamily: customFont,
        fontWeight: '600',
    },
    commentText: {
        fontSize: 16,
        color: '#333333',
        lineHeight: 22,
        fontFamily: customFont,
    },
    completeButton: {
        backgroundColor: '#FB644C',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        alignItems: 'center',
    },
    completeButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontFamily: customFont,
        fontWeight: '600',
    },
    loadingText: {
        fontSize: 16,
        color: '#666666',
        marginTop: 20,
        textAlign: 'center',
        fontFamily: customFont,
        lineHeight: 22,
    },
    headerButtons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0F0F0',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 16,
        marginRight: 10,
    },
    editButtonText: {
        color: '#666666',
        fontSize: 14,
        marginLeft: 4,
        fontFamily: customFont,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        marginLeft: 4,
        fontFamily: customFont,
    },
    noFeedbackContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
    },
    noFeedbackTitle: {
        fontSize: 24,
        color: '#333333',
        fontFamily: customFont,
        fontWeight: '600',
        marginTop: 20,
        marginBottom: 16,
    },
    noFeedbackMessage: {
        fontSize: 16,
        color: '#666666',
        textAlign: 'center',
        lineHeight: 24,
        fontFamily: customFont,
        marginBottom: 30,
    },
    noFeedbackSaveButton: {
        backgroundColor: '#4CAF50',
        paddingHorizontal: 32,
        paddingVertical: 14,
        borderRadius: 25,
    },
    noFeedbackSaveButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontFamily: customFont,
        fontWeight: '600',
    },
});
