// styles/EmotionGridStyles.js
import { StyleSheet } from 'react-native';
import customFont from '../fonts';

export const emotionGridStyles = StyleSheet.create({
    emotionGrid: {
        flex: 1,
        marginBottom: 16,
    },
    emotionGridContent: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        paddingHorizontal: 6,
        paddingBottom: 20,
    },
    emotionCard: {
        borderRadius: 12,
        margin: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    emotionCardTouchArea: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 12,
        position: 'relative',
        paddingHorizontal: 1,
    },
    emotionCardText: {
        color: '#FFFFFF',
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
        fontFamily: customFont,
        lineHeight: 12,
    },
    selectedBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    selectedBadgeText: {
        color: '#4CAF50',
        fontSize: 10,
        fontFamily: customFont,
    },
    categoryGridContent: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
        paddingHorizontal: 10,
        paddingBottom: 20,
    },
    categoryCard: {
        borderRadius: 16,
        margin: 8,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
        justifyContent: 'space-between',
        width: '45%',
        minHeight: 110,
    },
    categoryCardTitle: {
        color: '#FFFFFF',
        fontSize: 24,
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
        fontFamily: customFont,
    },
    categoryCardDescription: {
        color: '#FFFFFF',
        fontSize: 16,
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
        fontFamily: customFont,
        marginBottom: 8,
        opacity: 0.9,
    },
    categoryCardCount: {
        color: '#FFFFFF',
        fontSize: 18,
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
        fontFamily: customFont,
    },
});
