
spring:
  application:
    name: Comma-Backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  exposed:
    generate-ddl: true
    show-sql: true

  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 1
      api-key: ${OPENAI_API_KEY}