name: Deploy server

on:
  push:
    branches: [ backend ]
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy server only
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/gamja/comma
            git pull origin backend
            
            cd Backend
            docker stop comma || true
            docker rm comma || true
            docker rmi comma || true
            docker build -t comma .
            docker run -d -p 8080:8080 --network gamjanet --name comma --env-file comma.env comma
            
            docker builder prune -f
